import type { Metadata } from 'next';
import { PageHero } from '@/components/page-hero';
import { siteConfig } from '@/lib/site';

export const metadata: Metadata = { title: 'Contact', description: 'Talk to Elite Resume Craft about your next career move.' };

export default function ContactPage() { return <><PageHero eyebrow="Contact" title={<>Let’s talk about <em>what’s next.</em></>} description="Tell us a little about the role you are pursuing and the support you are looking for." />
  <section className="section"><div className="shell contact-grid"><div className="contact-aside"><p className="eyebrow"><span /> Prefer a direct conversation?</p><h2>We are here to help you choose the right next step.</h2><div className="contact-detail"><span>Email</span><a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></div><div className="contact-detail"><span>WhatsApp</span><a href={`https://wa.me/${siteConfig.whatsapp.replace(/\D/g, '')}`}>{siteConfig.whatsapp}</a></div><p className="contact-small">For privacy, please do not send sensitive career documents through public social media messages.</p></div><form className="contact-form" action={`mailto:${siteConfig.email}`} method="post" encType="text/plain"><div className="form-row"><label>First name<input name="firstName" autoComplete="given-name" required /></label><label>Last name<input name="lastName" autoComplete="family-name" required /></label></div><label>Email address<input type="email" name="email" autoComplete="email" required /></label><label>What support are you looking for?<select name="service" defaultValue=""><option value="" disabled>Select a service</option><option>ATS Resume</option><option>Cover Letter</option><option>LinkedIn Optimization</option><option>Career Branding Suite</option><option>Not sure yet</option></select></label><label>Tell us about your next move<textarea name="message" rows={5} placeholder="Your target role, industry, or what you would like to improve..." required /></label><button className="button button--gold" type="submit">Send enquiry <span>↗</span></button><p className="form-footnote">The client portal and secure intake form launch in Milestone 2. This form opens your email client.</p></form></div></section>
  </>; }
