import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { ArrowUpRight } from '@/components/icons';
import { articles } from '@/lib/content';

export function generateStaticParams() { return articles.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: { slug: string } }): Metadata { const article = articles.find(item => item.slug === params.slug); return article ? { title: article.title, description: article.excerpt } : {}; }

export default function ArticlePage({ params }: { params: { slug: string } }) { const article = articles.find(item => item.slug === params.slug); if (!article) notFound(); return <article className="article-page"><header className="article-page__header"><div className="shell"><p className="eyebrow eyebrow--light"><span /> {article.category}</p><h1>{article.title}</h1><p>{article.excerpt}</p><span>{article.date} · {article.readTime}</span></div></header><div className="shell article-page__body"><p className="article-page__lead">A stronger application is rarely about finding more impressive words. It is about making the work you have already done easier to understand, trust, and remember.</p><h2>Start with the outcome, not the task.</h2><p>When you describe experience, lead with the difference your work made. Then add the actions, scope, collaborators, or tools that make the result feel specific. This gives a reader a reason to care before asking them to process every detail.</p><p>Use facts you can stand behind. A clear, accurate example will always be more persuasive than a vague claim or an inflated metric.</p><blockquote>“The goal is not to sound bigger. It is to make the value of your work easier to see.”</blockquote><h2>Let the target role guide your selection.</h2><p>You do not need to include every responsibility from every role. Choose the examples that prove the capabilities most relevant to the opportunity ahead, then use language that feels natural to your industry and market.</p><div className="article-page__next"><p>Ready to put this into practice?</p><Link className="text-link text-link--arrow" href="/services/ats-resume">Explore ATS Resume support <ArrowUpRight /></Link></div></div></article>; }
